"""Meridian Analytics — People Dashboard (Overview page)."""
import pandas as pd
import plotly.express as px
import streamlit as st

from lib.data import (
    COLORS, DEPT_ORDER, LEVEL_ORDER, TODAY,
    apply_filters, load_employees, load_enps, load_flight_risk,
    load_hires, load_terminations, sidebar_filters,
)

st.set_page_config(
    page_title="Meridian People Analytics",
    page_icon="📊",
    layout="wide",
)

# ---- header
st.title("Meridian Analytics · People Dashboard")
st.caption(
    "A fictional 900-employee professional services firm. All data is synthetic. "
    "Use the sidebar filters to slice metrics by department or level. Use the page nav on the left to drill in."
)

emp = load_employees()
terms = load_terminations()
hires = load_hires()
enps = load_enps()
risk = load_flight_risk()

depts, levels = sidebar_filters(emp)
emp_f = apply_filters(emp, depts, levels)
active_f = emp_f[emp_f["is_active"]]

ONE_YEAR_AGO = TODAY - pd.Timedelta(days=365)

# ---- KPIs
active_count = len(active_f)
one_yr_ago_active = emp_f[
    (emp_f["hire_date"] <= ONE_YEAR_AGO)
    & (emp_f["termination_date"].isna() | (emp_f["termination_date"] > ONE_YEAR_AGO))
]
hc_yoy = active_count - len(one_yr_ago_active)

recent_terms = terms[
    (terms["termination_date"] >= ONE_YEAR_AGO)
    & terms["department"].isin(depts)
    & terms["level"].isin(levels)
]
denom = max(1, (active_count + len(one_yr_ago_active)) / 2)
attrition_rate = len(recent_terms) / denom * 100

recent_hires = hires[
    (hires["start_date"] >= ONE_YEAR_AGO)
    & hires["department"].isin(depts)
    & hires["level"].isin(levels)
]
avg_tth = recent_hires["time_to_hire_days"].mean()

latest_survey_date = enps["survey_date"].max()
latest_enps = enps[enps["survey_date"] == latest_survey_date].merge(
    active_f[["employee_id"]], on="employee_id"
)
total_resp = len(latest_enps)
prom = (latest_enps["category"] == "Promoter").sum()
det = (latest_enps["category"] == "Detractor").sum()
enps_score = (prom - det) / max(1, total_resp) * 100

risk_in_scope = risk.merge(active_f[["employee_id"]], on="employee_id")
high_critical = risk_in_scope[risk_in_scope["flight_risk_band"].isin(["Critical", "High"])]

st.markdown("### At a glance")
c1, c2, c3, c4, c5 = st.columns(5)
c1.metric("Active Headcount", f"{active_count:,}", f"{hc_yoy:+d} YoY")
c2.metric("12-mo Attrition", f"{attrition_rate:.1f}%")
c3.metric("Time-to-Hire (12 mo avg)", f"{avg_tth:.0f} days" if pd.notna(avg_tth) else "—")
c4.metric("eNPS (Q1 2026)", f"{enps_score:+.0f}")
c5.metric(
    "High / Critical Flight Risk",
    f"{len(high_critical):,}",
    f"{len(high_critical)/max(1,active_count)*100:.0f}% of HC",
    delta_color="inverse",
)

st.divider()

# ---- Headcount over time
st.markdown("### Headcount over time")
month_starts = pd.date_range("2023-06-01", TODAY, freq="MS")
hc_rows = []
for d in month_starts:
    in_scope = emp_f[
        (emp_f["hire_date"] <= d)
        & (emp_f["termination_date"].isna() | (emp_f["termination_date"] > d))
    ]
    hc_rows.append({"month": d, "headcount": len(in_scope)})
hc_df = pd.DataFrame(hc_rows)
fig = px.line(hc_df, x="month", y="headcount", markers=False)
fig.update_traces(line=dict(color=COLORS["primary"], width=3))
fig.update_layout(height=300, margin=dict(t=10, b=0, l=0, r=0))
fig.update_yaxes(title=None)
fig.update_xaxes(title=None)
st.plotly_chart(fig, width="stretch")

# ---- Two-up composition snapshot
ca, cb = st.columns(2)
with ca:
    st.markdown("### Headcount by department")
    by_dept = (active_f.groupby("department").size()
               .reindex(DEPT_ORDER, fill_value=0).reset_index(name="count"))
    fig = px.bar(by_dept, x="count", y="department", orientation="h",
                 color_discrete_sequence=[COLORS["primary"]])
    fig.update_layout(height=320, margin=dict(t=10, b=0), showlegend=False)
    fig.update_yaxes(title=None, categoryorder="total ascending")
    fig.update_xaxes(title=None)
    st.plotly_chart(fig, width="stretch")

with cb:
    st.markdown("### Headcount by level")
    by_lvl = (active_f.groupby("level").size()
              .reindex(LEVEL_ORDER, fill_value=0).reset_index(name="count"))
    fig = px.bar(by_lvl, x="level", y="count",
                 category_orders={"level": LEVEL_ORDER},
                 color_discrete_sequence=[COLORS["primary"]])
    fig.update_layout(height=320, margin=dict(t=10, b=0), showlegend=False)
    fig.update_yaxes(title=None)
    fig.update_xaxes(title=None)
    st.plotly_chart(fig, width="stretch")

st.caption(
    "Data refresh: synthetic data is generated by `data_generator.py` and saved as CSVs. "
    "Date anchor: 2026-05-11."
)
